# frozen_string_literal: true

$LOAD_PATH.push File.expand_path('lib', __dir__)

# Maintain your gem's version:
require 'source_maps_fixer/version'

# Describe your gem and declare its dependencies:
Gem::Specification.new do |s|
  s.name        = 'source_maps_fixer'
  s.version     = SourceMapsFixer::VERSION
  s.authors     = ['Zbigniew Humeniuk']
  s.email       = ['hello@artofcode.co']
  s.homepage    = 'https://artofcode.co'
  s.summary     = 'Rake tasks for fixing URLs to source maps'
  s.description = 'Rake tasks that fix sourceMappingURL in JavaScript and ' \
                  'CSS bundles generated by webpack to match the final ' \
                  'fingerprinted names generated by Sprockets after ' \
                  "assets' precompilation"
  s.license     = 'MIT'

  s.files = Dir[
    '{app,config,db,lib}/**/*',
    'MIT-LICENSE',
    'Rakefile',
    'README.md'
  ]

  s.required_ruby_version = '>= 2.6.0'

  s.add_dependency 'rails', '>= 5.0', '< 7.0'

  s.add_development_dependency 'listen'
  s.add_development_dependency 'rubocop'
end
